spring:
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    properties:
      javax.persistence.query.timeout: "${JAVAX_PERSISTENCE_QUERY_TIMEOUT:30000}"
    open-in-view: false
    hibernate:
      ddl-auto: "create"
    database-platform: "${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}"
  datasource:
    driverClassName: "${SPRING_DRIVER_CLASS_NAME:org.postgresql.Driver}"
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}"
    username: "${SPRING_DATASOURCE_USERNAME:postgres}"
    password: "${SPRING_DATASOURCE_PASSWORD:123456}"
    hikari:
      maximumPoolSize: "${SPRING_DATASOURCE_MAXIMUM_POOL_SIZE:16}"

security:
  jwt:
    access-token-exp-ms: "${JWT_ACCESS_TOKEN_EXP_MS:9000}" # Number of seconds (2.5 hours)
    refresh-token-exp-ms: "${JWT_REFRESH_TOKEN_EXP_MS:604800}" # Number of seconds (1 week)
    issuer: "${JWT_ISSUER}:com.iot.issuer"
    signing-key: "${JWT_SIGNING_KEY}: com.iot.signingkey"